//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homecare.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caretaker
    {
        public int id_caretaker { get; set; }
        public string caretaker_name { get; set; }
        public int fk_login_caretaker { get; set; }
        public Nullable<int> fk_phone_caretaker { get; set; }
    
        public virtual Login Login { get; set; }
    }
}
