//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homecare.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaretakerView
    {
        public string caretaker_name { get; set; }
        public int id_caretaker { get; set; }
        public string phone_number { get; set; }
        public string username { get; set; }
    }
}
