//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homecare.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class CaretakerView
    {
        [DisplayName("Fulde navn")]
        public string caretaker_name { get; set; }
        public int id_caretaker { get; set; }

        [DisplayName("Telefon")]
        public string phone_number { get; set; }

        [DisplayName("Mail")]
        public string username { get; set; }
    }
}
