//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homecare.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Route_Details = new HashSet<Route_Details>();
        }
    
        public int id_patient { get; set; }
        public string patient_name { get; set; }
        public string cpr { get; set; }
        public string relative_phonenumber { get; set; }
        public int fk_address_patient { get; set; }
        public Nullable<int> fk_phone_patient { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Phone Phone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Route_Details> Route_Details { get; set; }
    }
}
