//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homecare.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteView
    {
        public System.TimeSpan arrival { get; set; }
        public string caretaker_name { get; set; }
        public string road_name { get; set; }
        public string number { get; set; }
        public string city_name { get; set; }
        public string zipcode { get; set; }
        public string patient_name { get; set; }
    }
}
